// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MyData {
    #[prost(message, repeated, tag="1")]
    pub jup: ::prost::alloc::vec::Vec<super::super::sf::solana::r#type::v1::ConfirmedTransaction>,
    #[prost(message, repeated, tag="2")]
    pub usdt: ::prost::alloc::vec::Vec<super::super::sf::solana::r#type::v1::ConfirmedTransaction>,
}
// @@protoc_insertion_point(module)
